### ISSUE TITLE
The package isn't available via PyPI service

### ISSUE THREAD

**Issue by amarynets** [DusanMadar/TorIpChanger#1]
Hi
Did you add your package to PyPI? It can't be installed from there

**Comment by DusanMadar** [comment]
TorIpChanger is not on PyPi. You can install it with `pip` directly from `GitHub`, see https://stackoverflow.com/q/20101834/4183498 for more details.

**Comment by DusanMadar** [comment]
https://pypi.org/project/toripchanger/
