### ISSUE TITLE
ConnectionRefusedError: [Errno 111] Connection refused when requesting for new IP after the first time.

### ISSUE THREAD

**Issue by amrittb** [DusanMadar/TorIpChanger#2]
First IP is renewed properly, however subsequent IPs are not properly renewed and throws the following error.

Terminal traceback.
```
Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/stem/socket.py", line 525, in _make_socket
    control_socket.connect((self.address, self.port))
    ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:raceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
        result = g.send(result)
    File "/usr/local/lib/python3.6/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
        response = yield method(request=request, spider=spider)
    File "/usr/app/crawler/products/products/middlewares.py", line 149, in process_request
        new_ip = ip_changer.get_new_ip()
    File "/usr/local/lib/python3.6/site-packages/toripchanger/changer.py", line 113, in get_new_ip
        self._obtain_new_ip()
    File "/usr/local/lib/python3.6/site-packages/toripchanger/changer.py", line 179, in _obtain_new_ip
        with Controller.from_port(port=self.tor_port) as controller:
    File "/usr/local/lib/python3.6/site-packages/stem/control.py", line 1021, in from_port
        control_port = stem.socket.ControlPort(address, port)
    File "/usr/local/lib/python3.6/site-packages/stem/socket.py", line 493, in __init__
        self.connect()
    File "/usr/local/lib/python3.6/site-packages/stem/socket.py", line 176, in connect
        self._socket = self._make_socket()
    File "/usr/local/lib/python3.6/site-packages/stem/socket.py", line 528, in _make_socket
        raise stem.SocketError(exc)
    stem.SocketError: [Errno 111] Connection refused
```

Here's the middleware file

```python

# A Tor IP will be reused only after 10 different IPs were used.
ip_changer = TorIpChanger(reuse_threshold=10, local_http_proxy=os.environ['LOCAL_HTTP_PROXY'], tor_password=os.environ['TOR_PASSWORD'], tor_port=int(os.environ['TOR_PORT']))

# LOCAL_HTTP_PROXY=127.0.0.1
# TOR_PASSWORD=tor_password
# TOR_PORT=9051

class ProxyMiddleware(object):
    _requests_count = 0

    def process_request(self, request, spider):
        self._requests_count += 1
        if self._requests_count > 10:
            spider.log('Renewing IP after %s requests' % (self._requests_count - 1))
            self._requests_count = 0 
            new_ip = ip_changer.get_new_ip()
            spider.log('New IP: %s' % new_ip)

        request.meta['proxy'] = os.environ['LOCAL_HTTP_PROXY']
```

**Comment by amrittb** [comment]
Yes, the python script was getting new IPs multiple times. I kind of figured out the problem. It's like you suggested. I am sending concurrent requests from Scrapy, so multiple requests are hitting the middleware and trying to get new IP after a certain number of requests. I created a class variable on the middleware with the flag to check if the Stem is busy getting the IP. This process gets exactly 2 new IPs then the request to http://icanhazip.com is not sent on the third IP fetch. 
Successful IP renew logs:
```
se-crawler     | 2019-01-08 01:21:03 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): tor-privoxy:8118
se-crawler     | 2019-01-08 01:21:04 [urllib3.connectionpool] DEBUG: http://tor-privoxy:8118 "GET http://icanhazip.com/ HTTP/1.1" 200 15
se-crawler     | 2019-01-08 01:21:04 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): icanhazip.com:80
se-crawler     | 2019-01-08 01:21:05 [urllib3.connectionpool] DEBUG: http://icanhazip.com:80 "GET / HTTP/1.1" 200 13
```

Failure IP logs:
```
se-crawler     | 2019-01-08 01:21:35 [urllib3.connectionpool] DEBUG: Starting new HTTP connection (1): tor-privoxy:8118
se-crawler     | 2019-01-08 01:21:36 [urllib3.connectionpool] DEBUG: http://tor-privoxy:8118 "GET http://icanhazip.com/ HTTP/1.1" 200 15
```

There was no second request sent to http://icanhazip.com when the error happened.

**Comment by DusanMadar** [comment]
> There was no second request sent to http://icanhazip.com when the error happened.

There are two requests to http://icanhazip.com in your first example. But, one is **through Tor** (`http://tor-privoxy:8118 "GET http://icanhazip.com/ HTTP/1.1" 200 15`)  to get Tor's IP and the other is a **direct one** (`http://icanhazip.com:80 "GET / HTTP/1.1" 200 13`) to get your actual IP. Tor/stem often returns your real IP after requesting a new IP and obviously you don't want to scrape using your real IP address.

Real IP is checked only once and then stored by TorIpChanger and compared to each new Tor IP (see https://github.com/DusanMadar/TorIpChanger/blob/master/toripchanger/changer.py#L135).

**Comment by DusanMadar** [comment]
Back to `stem.SocketError: [Errno 111] Connection refused`.

As stated above - that error suggests Tor is not running.

Try running `service tor status` in terminal (assuming you're on Unix/Linux) after you get that message to see if Tor is running or not.

Other thing you should try is to run a single instance of your scraper (i.e. not parallelized) and see if IP changing works.

**Comment by amrittb** [comment]
I am running docker-containers for Tor and Privoxy using ```dockage/tor-privoxy```. I tried non-concurrent requests from Scrapy but the result was same. First IP was resolved correctly, however subsequent IPs were not resolved even if Tor service was running. I tried using the same docker container for getting new IPs. I am getting new IPs everytime. It seems the problem is specific to scrapy.

`python
import time
from toripchanger import TorIpChanger

if __name__ == "__main__":
    ip_changer = TorIpChanger(tor_port=9051, local_http_proxy='127.0.0.1:8118')

    for i in range(10):
        ip = ip_changer.get_new_ip()

        print("New IP: " + ip)

        time.sleep(5)
`

**Comment by amrittb** [comment]
The dockage/tor-privoxy does everything that you have mentioned in the SO question. https://stackoverflow.com/questions/45901892/how-to-connect-to-tor-control-port-9051-from-a-remote-host 

The container works perfectly for the above test script.

**Comment by DusanMadar** [comment]
`TorIpChanger` expects Tor and Privoxy run locally. `dockage/tor-privoxy` container provides this by exposing control ports to host and hence that should be fine. But how is it possible that the IP is changed only the first time is still a mystery to me.

**Comment by amrittb** [comment]
I dug deeper into the problem and figured out somewhat what was happening. I created tor-privoxy docker image from scratch and it had the same problem. Even when both Tor and Privoxy were running and listening to ports 9050, 8118 and 9051 in some instances the socket was closed prematurely when the response from the particular port was empty content. I suspected this was due to the Inter-Container Networking of Docker. 

When one container is trying to connect to another container using Docker Network. It throws the error because of IP of the tor-privoxy container not matching 127.0.0.1. Even when correct IP was passed for `controller.from_port(address='container_ip',port=9051)` the connection was not successful.

**Comment by amrittb** [comment]
I did managed to make TorIpChanger work by merging both tor-privoxy and scrapy containers into single one. That's is kind of messy.

**Comment by DusanMadar** [comment]
Hi, it took me quite a long time but I figured out what was causing `stem.SocketError: [Errno 111] Connection refused`.
There's a new version (`toripchanger==1.1.0`) with which it is possible to change IP of a remote Tor. README was also updated, please check for more details.

**Comment by shamiul94** [comment]
Just restart tor after editing the `torrc` file. 
```
sudo service tor restart
```
