### ISSUE TITLE
ip not changing

### ISSUE THREAD

**Issue by eloiup** [DusanMadar/TorIpChanger#3]
Hi!
I am trying to use toripchanger to webscrap a site that has a limited amount of requesitions.

After setting it up i though i was good to go but soon i got '429.
So I tried a basic example with Icanhazip and it worked.
So i tried a different website (api.myip) and it didnt work (got my original IP)

What is happening? Am I or am I not using a different IP as a proxy?

sample code:

```
import requests
from toripchanger import TorIpChanger

headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'}

tor_ip_changer = TorIpChanger(tor_password='password1', tor_port=9051, local_http_proxy='127.0.0.1:8118', new_ip_max_attempts=50000, reuse_threshold=0)
tor_ip_changer.get_new_ip()

>> New IP

requests.get('http://icanhazip.com/', headers=headers, proxies={'http': '127.0.0.1:8118'}).content

>> New IP

requests.get('https://api.myip.com/', headers=headers, proxies={'http': '127.0.0.1:8118'}).content

>> Original IP
```

**Comment by DusanMadar** [comment]
Dude, you scared the hell out of me :smile:.

I tried your example and yes, a request to 'https://api.myip.com/' returns real IP. The reason is simple, though - one missing `s` in proxy **protocol** settings which changes the key from `http` to `https`.

Change `proxies={'http': '127.0.0.1:8118'}` to `proxies={'https': '127.0.0.1:8118'}` -->
```
requests.get('https://api.myip.com/', headers=headers, proxies={'https': '127.0.0.1:8118'}).content

>> New IP
```

**Comment by DusanMadar** [comment]
Also, you can use `https://check.torproject.org/` to check if Tor is leveraged.

**Comment by eloiup** [comment]
oh lol...

spent over 2 hours last night trying to figure it out before reaching out.

ty, sorry about that

**Comment by DusanMadar** [comment]
Now worries. Details like this one are often very difficult to spot.
