### ISSUE TITLE
How to handle multiple scrapy processes using TorIpChanger?

### ISSUE THREAD

**Issue by osenv** [DusanMadar/TorIpChanger#7]
Hi,

Thanks for this excellent tool which works perfectly fine on my ubuntu server.

I have a question, do I need to use multitor (https://github.com/trimstray/multitor) to run multiple instances?

Now I am currently running about 20 processes for crawling different sites, in each process there is method to call get_new_ip() after 10 requests reached, which I think this may not be good or best practice.

If I only get one machine, and running 20 processes, should I remove calling get_new_ip in each process and use TorIpChanger seperately, like to make a crontab to change the exit ip every minute?

Really appreciate this lib and have a nice day!
BR

**Comment by DusanMadar** [comment]
> do I need to use multitor (https://github.com/trimstray/multitor) to run multiple instances?

Yes. Another alternative is https://github.com/mattes/rotating-proxy. I was also thinking about writing a docker-compose and TorIpChanger based rotating Tor proxy but didn't get to it ...

> Now I am currently running about 20 processes for crawling different sites, in each process there is method to call get_new_ip() after 10 requests reached, which I think this may not be good or best practice.

Well, personally I think changing IP after 10 requests is too often.

Do I get it right you scrape those 20 sites simultaneously? If that's the case, I would somehow sync the requests, meaning I would change IP only after requests to all 20 sites were handled. This way each of those sites will be scraped from a different IP and at the same time you wont hit the fast responding sites too much as you will have to wait for the slowest one. You shouldn't hammer the target site too hard in general (sleeps between requests, etc)

Your suggestion of using a cron job may result in changing IP mid request and I don't know if you would get the response back [I don't know if Tor waits till all requests are finished before changing circuit].

**Comment by osenv** [comment]
Yes, simultaneously scraping 20 sites on one server.  Thanks for your suggestions and I'll experiment on that ^^

Thank you.
