### ISSUE TITLE
toripchanger.exceptions.TorIpError: Failed to obtain a new usable Tor IP

### ISSUE THREAD

**Issue by freephys** [DusanMadar/TorIpChanger#8]
Get following error even when increasing to 1000 times. 
Python 3.6.9 and ubuntu env.
What is the env that this has been successfully run? 
Thanks

>>> current_ip = tor_ip_changer_0.get_new_ip()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lkhf/.local/lib/python3.6/site-packages/toripchanger/changer.py", line 113, in get_new_ip
    raise TorIpError("Failed to obtain a new usable Tor IP")
toripchanger.exceptions.TorIpError: Failed to obtain a new usable Tor IP

>>> tor_ip_changer_0 = TorIpChanger(reuse_threshold=0,new_ip_max_attempts=100)
>>> current_ip = tor_ip_changer_0.get_new_ip()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lkhf/.local/lib/python3.6/site-packages/toripchanger/changer.py", line 113, in get_new_ip
    raise TorIpError("Failed to obtain a new usable Tor IP")
toripchanger.exceptions.TorIpError: Failed to obtain a new usable Tor IP

**Comment by DusanMadar** [comment]
I've tested with Ubuntu 18.04 and Python 3.6. Can you confirm you can change IP manually? For example by following https://gist.github.com/DusanMadar/8d11026b7ce0bce6a67f7dd87b999f6b.

**Comment by freephys** [comment]
thanks, needs to update config  with https://askubuntu.com/questions/1046432/tor-service-not-really-working. Furthermore, do you have ideas about applying it in multithread case say each thread get a different ip?

**Comment by DusanMadar** [comment]
> say each thread get a different ip

In that case you would need a separate Tor instance per process. Take a look at https://github.com/mattes/rotating-proxy.
