### ISSUE TITLE
Support for using HTTPS with ICanHazIp.com

### ISSUE THREAD

**Issue by gaby** [DusanMadar/TorIpChanger#9]
@DusanMadar The icanhazip website has support for https via https://icanhazip.com 

They also have now:
- https://ipv4.icanhazip.com
- https://ipv6.icanhazip.com

Would it be possible for you to add support for specifying which one to use?

**Comment by DusanMadar** [comment]
Hi @gaby, sorry for late response. I can definitely make an update to use https://icanhazip.com/.

About the ipv4 vs ipv6, I'll look at the code base, but cannot promise that this will get implemented.

**Comment by gaby** [comment]
@DusanMadar That's fine since adding those other two would add too much complexity.

**Comment by DusanMadar** [comment]
Version 1.2.0 released.

**Comment by gaby** [comment]
> Version 1.2.0 released.

Awesome! Thank you! 💪
